/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Word;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class ChartPane extends javax.swing.JPanel {

    private DefaultTableModel datos;
    
    public ChartPane() {
        try {
            initComponents();
            datos = new DefaultTableModel();
            datos.addColumn("Word");
            datos.addColumn("Meaning");
            datos.addColumn("Insertion Date");
            jTable1.setModel(datos);
            
            int i=1;
            for (Word w : Word.selectWhere(null)) {
                Object object[]=new Object[]{w.getWord(),w.getMeaning(),w.getInsertionDate()};
                datos.addRow(object);
//                datos.addColumn(w.getMeaning());
//                datos.setValueAt(w.getWord(), i, 1);
//                datos.setValueAt(w.getMeaning(), i, 2);
//                datos.setValueAt(w.getInsertionDate(), i, 3);
//                i++;
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Word", "Meaing", "InsertionDate"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
