package view;

import Model.MakeVocabulary;
import Model.Word;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


public class InsertingTextPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsertingText
     */
    public InsertingTextPanel() {
        initComponents();
    }

//    @Override
//    public void setVisible(boolean aFlag) {
//        if(!aFlag)
//            eraseText();
//        super.setVisible(aFlag); 
//    }
//    private void eraseText(){
//        jTAImput.setText("");
//        jTAOutput.setText("");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSPImput = new javax.swing.JScrollPane();
        jTAImput = new javax.swing.JTextArea();
        jBCreate = new javax.swing.JButton();
        JBCopy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAOutput = new javax.swing.JTextArea();
        jBSelect = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jTAImput.setColumns(20);
        jTAImput.setRows(5);
        jSPImput.setViewportView(jTAImput);

        jBCreate.setText("Create");
        jBCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateActionPerformed(evt);
            }
        });

        JBCopy.setText("Copy");
        JBCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCopyActionPerformed(evt);
            }
        });

        jTAOutput.setColumns(20);
        jTAOutput.setRows(5);
        jScrollPane2.setViewportView(jTAOutput);

        jBSelect.setText("Select");
        jBSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCopy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSelect)
                .addContainerGap(547, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSPImput, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCreate)
                    .addComponent(JBCopy)
                    .addComponent(jBSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPImput, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCopyActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection data = new StringSelection(this.jTAOutput.getText());
        clipboard.setContents(data, data);
    }//GEN-LAST:event_JBCopyActionPerformed

    private void jBCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateActionPerformed
        ArrayList list=MakeVocabulary.makeVocabulary(jTAImput.getText());
        String listaPalabras="";
        for (Object list1 : list) {
            try {
                Word w= new Word((String) list1);
                listaPalabras+="\n"+w.getWord()+" = ";
                if(!w.exist()){
                    w.insert();
                    System.out.println("palabra "+(String)list1+" insertada");
                }
                    
            } catch (SQLException ex) {
                Logger.getLogger(InsertingTextPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTAOutput.setText(listaPalabras);
    }//GEN-LAST:event_jBCreateActionPerformed

    private void jBSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelectActionPerformed
        try {
            ArrayList<Word> l=Word.selectWhere(null);
            String outPut="";
            for (Word l1 : l) {
                outPut+=l1.getWord()+" = "+l1.getMeaning()+"\n";
            }
            jTAOutput.setText(outPut);
        } catch (SQLException ex) {
            Logger.getLogger(InsertingTextPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCopy;
    private javax.swing.JButton jBCreate;
    private javax.swing.JButton jBSelect;
    private javax.swing.JScrollPane jSPImput;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAImput;
    private javax.swing.JTextArea jTAOutput;
    // End of variables declaration//GEN-END:variables
}
