/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author yoportatil
 */
public class InsertingText extends javax.swing.JPanel {

    /**
     * Creates new form InsertingText
     */
    public InsertingText() {
        initComponents();
    }

    @Override
    public void setVisible(boolean aFlag) {
        if(!aFlag)
            eraseText();
        super.setVisible(aFlag); 
    }
    private void eraseText(){
        jTAImput.setText("");
        jTAOutput.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSPImput = new javax.swing.JScrollPane();
        jTAImput = new javax.swing.JTextArea();
        jBCreate = new javax.swing.JButton();
        JBCopy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAOutput = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(550, 350));

        jTAImput.setColumns(20);
        jTAImput.setRows(5);
        jSPImput.setViewportView(jTAImput);

        jBCreate.setText("Create");

        JBCopy.setText("Copy");
        JBCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCopyActionPerformed(evt);
            }
        });

        jTAOutput.setColumns(20);
        jTAOutput.setRows(5);
        jScrollPane2.setViewportView(jTAOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPImput, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBCopy)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCreate)
                    .addComponent(JBCopy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPImput, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBCopyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCopy;
    private javax.swing.JButton jBCreate;
    private javax.swing.JScrollPane jSPImput;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAImput;
    private javax.swing.JTextArea jTAOutput;
    // End of variables declaration//GEN-END:variables
}
